name: Pull Request

on:
  pull_request_target:
    types: ['opened', 'reopened', 'edited']

jobs:
  test-semantic-release:
    name: Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Config git
        run: |
          git config --local user.email "30906710+traefiker@users.noreply.github.com"
          git config --local user.name "traefiker"

      - name: Create dry branch
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          script: |
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'heads/dry'
              });
            } catch (e) {}
            try {
              await github.rest.git.createRef({
                ref: 'refs/heads/dry',
                sha: context.sha,
                ...context.repo
              })
            } catch (e) {}

      - name: Checkout dry branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: dry

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Dry run with commits
        id: dry-run-commits
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require('./semantic-release-dry.js')
            return await script({require})

      - name: Squash commits into PR title
        run: |
          git reset --soft HEAD^
          git commit -m '${{ github.event.pull_request.title }}'
          git push --force

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Dry run squashed PR
        id: dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require('./semantic-release-dry.js')
            return await script({require})

      - name: Back to code
        uses: actions/checkout@v2

      - name: Clear dry branch
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          script: |
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/dry'
            });

      - name: 'Release notes preview comment'
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          script: |
            const header = '# :spiral_notepad: Release notes preview\n\n';
            const headerCommits = '# :mag: Release notes preview from commits\n\n<details>\n\n';

            const body = header + `${{ steps.dry-run.outputs.result }}` + '\n\n' + headerCommits + `${{ steps.dry-run-commits.outputs.result }}` + '\n\n</details>';
            await github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
